### PR TITLE
Player support for webOS Standard Web API

### PR DESCRIPTION
**Pull request by PierreAronnax**
Video playback working
Controls working
Subtitles working (with working Disable)
Audio languages not working
Buffering indicator added
Misc. improvements

### CODE REVIEW

**Comment by simonjhogan** [comment]
I'll have to confirm this works on the netcast platform before merging ... would have been better to set an option to use html5 player rather than netcast object ...

S

**Comment by PierreAronnax** [comment]
Sorry, I didn't realize this project was also for netcast models. If I knew I definitely would have done things differently (don't replace things).

We could move all changes in player.js to a new player-webos.js and modify player.html to dynamically create either a <object> or a <video> and load the right script. The changes to plex.js and player.css should be compatible.
Or we could create a branch when we expect more incompatible changes in the future.

**Comment by simonjhogan** [comment]
All good I want to maintain one code base not separate branches ...,would prefer as I said to just have an option to select html5 player rather than Netcast instead of two player scripts ...

S

**Comment by simonjhogan** [comment]
do you want to look at allowing for an option for standard netcast or html? Just need to determine whether to do it myself ... I

**Comment by PierreAronnax** [comment]
Do what you think is best. At the moment I don't have the time to do such a big rewrite.
Personally I think making it an option makes a bad user experience. It should just work out of the box without the user having to change an option first.
At least make the default value platform dependent.

**Comment by fkick** [comment]
Hi Simon, have you reached any decision in regards to allowing an HTML 5 player for the webOS units?

**Comment by simonjhogan** [comment]
Yeah happy for it be integrated I just don’t have time to implement it.

S

**Comment by ryballs** [comment]
If this could be implemented some time in future it would be much
appreciated.

**Comment by DarthSim** [comment]
It would be great to see this on TV. :+1: Subtitles that can't be disabled or changed are annoying as hell.

**Comment by jrstravino** [comment]
Subtitle Unicode suport please.
The subtitles its not showing the all sentence if there is a pt-br letter like ı á  ç ...

**Pull request closed without merging**
